BACKBONE2D:
  YOLOv8:
    ver : m

    PRETRAIN:
      n : null
      s : null 
      m : weights/backbone2D/YOLOv8/v8_m.pth
      l : weights/backbone2D/YOLOv8/v8_l.pth
      x : null

BACKBONE3D:
  SHUFFLENETv2:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.25x : null
      width_mult_0.5x  : null
      width_mult_1.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_1.0x_RGB_16_best.pth
      width_mult_1.5x  : null
      width_mult_2.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_2.0x_RGB_16_best.pth
      
  I3D:
    PRETRAIN:
      default: weights/backbone3D/I3D/rgb_imagenet.pth
  
  RESNEXT:
    ver : 101

    PRETRAIN:
      ver_101 : weights/backbone3D/resnext/resnext-101-kinetics.pth

LOSS:
  TAL:
    top_k  : 10
    alpha  : 0.5
    beta   : 6.0
    radius : 2.5

    scale_cls_loss : 0.5
    scale_box_loss : 7.5
    scale_dfl_loss : 1.5

  SIMOTA:
    top_k  : 10
    gamma  : 0.5
    radius : 2.5

    dynamic_k     : False
    dynamic_top_k : 40

    scale_cls_loss : 0.5
    scale_box_loss : 7.5
    scale_dfl_loss : 1.5

config_path       : config/ucf_config.yaml
dataset           : ucf
loss              : tal
active_checker    : True
num_classes       : 24
backbone2D        : yolov8
backbone3D        : i3d
fusion_module     : CFAM
mode              : decoupled
interchannels     : [256, 256, 256]
pretrain_path     : /home/manh/checkpoint/88.24_ucf(i3d)/ema_epoch_7.pth
data_root         : /home/manh/Datasets/UCF101-24/ucf242
clip_length       : 16
batch_size        : 8
num_workers       : 6
acc_grad          : 16
lr                : 0.0001
weight_decay      : 0.0005
max_step_warmup   : 500
adjustlr_schedule : [1, 2, 3, 4, 5]
max_epoch         : 7
lr_decay          : 0.5
save_folder       : weights/model_checkpoint
sampling_rate     : 1


idx2name:
  0  : Baseketball
  1  : BaseketballDunk
  2  : Biking
  3  : CliffDiving
  4  : CricketBowling
  5  : Diving
  6  : Fencing
  7  : FloorGymnastics
  8  : GolfSwing
  9  : HorseRiding
  10 : IceDancing
  11 : LongJump
  12 : PoleVault
  13 : RopeClimbing
  14 : SalsaSpin
  15 : SkateBoarding
  16 : Skiing
  17 : Skijet
  18 : Soccer Juggling
  19 : Surfing
  20 : TennisSwing
  21 : TrampolineJumping
  22 : VolleyballSpiking
  23 : WalkingWithDog